In [2]:
import numpy as np

In [11]:
# create 5 points in linear space from 0 to 1 (including boundaries)
x = np.linspace(0,1,5)
x

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
x.shape

(5,)

In [13]:
# create vertical vector
y = x.reshape(-1,1)
y

array([[0.  ],
       [0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [14]:
y.shape

(5, 1)

In [58]:
x0, x1 = np.meshgrid(
        np.linspace(0, 1, 2, dtype=np.int).reshape(-1, 1),
        np.linspace(0, -2, 3, dtype=np.int).reshape(-1, 1),
    )

In [59]:
x0

array([[0, 1],
       [0, 1],
       [0, 1]])

In [60]:
x1

array([[ 0,  0],
       [-1, -1],
       [-2, -2]])

In [61]:
x1.shape

(3, 2)

In [62]:
# go over all points in 3 x 2 mesh
for i in range(x1.shape[0]):
    for j in range(x1.shape[1]):
        print(x0[i,j], x1[i,j])

0 0
1 0
0 -1
1 -1
0 -2
1 -2


In [68]:
# same thing in numpy (similar to zip in python lists)
X_new = np.c_[x0.ravel(), x1.ravel()]
X_new

array([[ 0,  0],
       [ 1,  0],
       [ 0, -1],
       [ 1, -1],
       [ 0, -2],
       [ 1, -2]])

In [69]:
x0.ravel()

array([0, 1, 0, 1, 0, 1])

In [70]:
x1.ravel()

array([ 0,  0, -1, -1, -2, -2])